Traceback (most recent call last):
  File "/home/dariusbarsony/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/dariusbarsony/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/dariusbarsony/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/dariusbarsony/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/dariusbarsony/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/dariusbarsony/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/dariusbarsony/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/dariusbarsony/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fields = ['data']

for b in books: 
    
    with open('extract_' + b + '.csv', 'w') as csvfile:

        # creating a csv writer object 
        csvwriter = csv.writer(csvfile) 
         
        # writing the fields 
        csvwriter.writerow(fields) 

        reader = PdfReader(dirname + b + '.pdf')
        for pagei in range(len(reader.pages)):
            page = reader.pages[pagei]
            csvwriter.writerow([page.extract_text()])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 13[0m
[1;32m     10[0m [38;5;66;03m# writing the fields [39;00m
[1;32m     11[0m csvwriter[38;5;241m.[39mwriterow(fields) 
[0;32m---> 13[0m reader [38;5;241m=[39m [43mPdfReader[49m(dirname [38;5;241m+[39m b [38;5;241m+[39m [38;5;124m'[39m[38;5;124m.pdf[39m[38;5;124m'[39m)
[1;32m     14[0m [38;5;28;01mfor[39;00m pagei [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;28mlen[39m(reader[38;5;241m.[39mpages)):
[1;32m     15[0m     page [38;5;241m=[39m reader[38;5;241m.[39mpages[pagei]

[0;31mNameError[0m: name 'PdfReader' is not defined
NameError: name 'PdfReader' is not defined

